apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.application.name }}"
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.application.name } }
  template:
    metadata:
      labels:
        app: { { .Values.application.name } }
    spec:
      container:
        - name: { { .Values.application.name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.application.port } }
