apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  name: nginx-ingress
  namespace: default
spec:
  tls:
    - hosts:
      - { { .Values.domain } }
      secretName: "{{ .Values.domain }}-tls"
  rules:
  - host: { { .Values.domain } }
    http:
      paths:
      - backend:
          service: 
            name: { { .Values.application.name } }
            port: { { .Values.application.port } }
        path: /
        pathType: Prefix