apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab.gnapp.dev.gasneiva.com
  namespace: gitlab
spec:
  secretName: "gitlab.gnapp.dev.gasneiva.com-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: gitlab.gnapp.dev.gasneiva.com
  dnsNames:
    - gitlab.gnapp.dev.gasneiva.com
