apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry.gnapp.dev.gasneiva.com
  namespace: gitlab
spec:
  secretName: "registry.gnapp.dev.gasneiva.com-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: registry.gnapp.dev.gasneiva.com
  dnsNames:
    - registry.gnapp.dev.gasneiva.com
