apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
spec:
  ports:
    - name: {{ .Values.application.name }}
      port: {{ .Values.application.port }}
      #targetPort: { { .Values.application.port } }
      protocol: TCP
  type: ClusterIp
  selector:
    app: {{ .Values.application.name }}
