apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      #- name: {{ .Values.application.name }}
      #  port: {{ .Values.application.port }}
      #  #targetPort: { { .Values.application.port } }
      #  protocol: TCP
  selector:
    app: {{ .Values.application.name }}
