apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.domain }}
spec:
  secretName: "{{ .Values.domain }}-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.domain }}
  dnsNames:
    - {{ .Values.domain }}
