apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/ingress.global-static-ip-name: "test-dev"
    cert-manager.io/cluster-issuer: letsencrypt
  name: {{ .Values.application.name }}
  namespace: default
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: "{{ .Values.domain }}-tls"
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.application.name }}
              port: 
                number: {{ .Values.service.port }}